name: Build and PVS-Studio analyze

on: [push]

env:
  BUILD_TYPE: Debug
  QT_VERSION: 6.6.1
  

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
            name: "Windows 2022 x64", 
            artifact: "Windows-x64.zip",
            os: windows-latest,
            analyzer_path: $ProgramFiles(x86)/PVS-Studio/CompilerCommandsAnalyzer.exe,
            converter_path: $ProgramFiles(x86)/PVS-Studio/HtmlGenerator.exe,
            environment_script: "$ProgramFiles(x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }
        #- {
        #    name: "Linux Latest x64", artifact: "Linux-x64.zip",
        #    os: ubuntu-latest
        #  }
        #- {
        #    name: "macOS Latest x64", artifact: "macOS-x64.zip",
        #    os: macos-latest
        #  }

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3.1.0
      with: 
        version: '${{env.QT_VERSION}}'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        modules: 'qtserialport'

    - name: Configure
      run: cmake -S . -B ${{github.workspace}}/build "-GVisual Studio 17 2022" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_EXPORT_COMPILE_COMMANDS=On "-DCMAKE_INSTALL_PREFIX=${{github.workspace}}/build/output"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j -- /m

    - name: Choco install PVS-Studio
      uses: crazy-max/ghaction-chocolatey@v3
      with: 
        args: install pvs-studio

    - name: Static analysis
      env:
          PVS_NAME: ${{ secrets.PVS_STUDIO_NAME }},
          PVS_KEY: ${{ secrets.PVS_STUDIO_KEY }}
      run: |
        ${{ matrix.config.analyzer_path }} credentials $PVS_NAME $PVS_KEY -o PVS.lic 
        ${{ matrix.config.analyzer_path }} analyze -f build/compile_commands.json -l PVS.lic -o PVS-Studio.log --disableLicenseExpirationCheck -j
        ${{ matrix.config.converter_path }} -a all -t sarif -o pvs-report.sarif PVS-Studio.log

    - name: Publish static analysis report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: pvs-report.sarif
        category: PVS-Studio
