name: Build and PVS-Studio analyze

on: [push]

env:
  BUILD_TYPE: Debug
  QT_VERSION: 6.6.1

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 20
    strategy:
      matrix:
        config:
        - {
            name: "Windows 2022 x64", 
            artifact: "Windows-x64.zip",
            os: windows-latest,
            analyzer_path: "C:/Program Files (x86)/PVS-Studio/CompilerCommandsAnalyzer.exe",
            converter_path: "C:/Program Files (x86)/PVS-Studio/HtmlGenerator.exe"
          }
        #- {
        #    name: "Linux Latest x64", artifact: "Linux-x64.zip",
        #    os: ubuntu-latest
        #  }
        #- {
        #    name: "macOS Latest x64", artifact: "macOS-x64.zip",
        #    os: macos-latest
        #  }

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3.1.0
      with: 
        version: '${{env.QT_VERSION}}'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        modules: 'qtserialport'

    - name: Choco install tools
      uses: crazy-max/ghaction-chocolatey@v3
      with: 
        args: install pvs-studio ninja

    - name: Initialize MSVC development environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure
      run: cmake -S . -B ${{github.workspace}}/build "-GNinja" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_EXPORT_COMPILE_COMMANDS=On "-DCMAKE_INSTALL_PREFIX=${{github.workspace}}/build/output"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Static analysis
      env:
          PVS_NAME: ${{ secrets.PVS_STUDIO_NAME }}
          PVS_KEY: ${{ secrets.PVS_STUDIO_KEY }}
      shell: pwsh
      run: |
        Start-Process -FilePath "${{ matrix.config.analyzer_path }}" -NoNewWindow -Wait -ArgumentList "credentials", "$env:PVS_NAME", "$env:PVS_KEY", "-o", "PVS.lic"
        Start-Process -FilePath "${{ matrix.config.analyzer_path }}" -NoNewWindow -Wait -ArgumentList "analyze", "-f", "${{github.workspace}}/build/compile_commands.json", "-R", "${{github.workspace}}/.PVS-Studio/analyze.pvsconfig", "-l", "PVS.lic", "-o", "PVS-Studio.log", "-j" 
        Start-Process -FilePath "${{ matrix.config.converter_path }}" -NoNewWindow -Wait -ArgumentList "-a", "all", "-t", "sarif", "-o", "pvs-report.sarif", "PVS-Studio.log"

    - name: Publish static analysis report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: pvs-report.sarif
        category: PVS-Studio
